---
- name: Upload verification script
  copy:
    src: "files/vms-before-ceph-version.sh"
    dest: "/root/vms-before-ceph-version.sh"
    owner: root
    group: root
    mode: 500
  tags: script
  no_log: true
- name: Run verification script
  shell: "/root/vms-before-ceph-version.sh"
  changed_when: False
