---
- name: Upload verification script
  copy:
    src: "files/vms-before-ceph-version.sh"
    dest: "/root/vms-before-ceph-version.sh"
    owner: root
    group: root
    mode: 500
  tags: script
  no_log: true

- name: Run verification script
  shell: "/root/vms-before-ceph-version.sh {% if ceph_version is defined %} -v {{ ceph_version }} {% endif %}"
  changed_when: False
  register: vms_list

- name: Print script output
  debug:
    var: vms_list.stdout_lines

- name: Clean verification script
  ansible.builtin.file:
    path: /root/vms-before-ceph-version.sh
    state: absent
